INSERT INTO WorkPosition VALUES(0, 'IT Staff', NULL, 0);
INSERT INTO WorkPosition VALUES(1, 'IT Vice Leader', NULL, 0);
INSERT INTO WorkPosition VALUES(2, 'IT Leader', NULL, 0);
INSERT INTO WorkPosition VALUES(3, 'HR Staff', NULL, 1);
INSERT INTO WorkPosition VALUES(4, 'HR Vice Leader', NULL, 1);
INSERT INTO WorkPosition VALUES(5, 'HR Leader', NULL, 1);
INSERT INTO WorkPosition VALUES(6, 'EE Staff', NULL, 2);
INSERT INTO WorkPosition VALUES(7, 'EE Vice Leader', NULL, 2);
INSERT INTO WorkPosition VALUES(8, 'EE Leader', NULL, 2);
INSERT INTO WorkPosition VALUES(9, 'ME Staff', NULL, 3);
INSERT INTO WorkPosition VALUES(10, 'ME Vice Leader', NULL, 3);
INSERT INTO WorkPosition VALUES(11, 'ME Leader', NULL, 3);
